### ISSUE TITLE
Diagram de clases_Abigail Coronel Santiago

### ISSUE THREAD

**Issue by abicoronel** [SistemasTecTlaxiaco/actividad-8-diagrama-de-clases-equipo_judith#4]
[Diagrama de clases.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-diagrama-de-clases-equipo_judith/files/10181159/Diagrama.de.clases.pdf)

**Comment by josealfredo79** [comment]
No esta evaluado...

**Comment by ElisabetRD** [comment]
50%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
